# Generated by Django 3.0.6 on 2020-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysdataset',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sysdataset',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
