# Generated by Django 3.0.6 on 2020-06-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200601_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdataset',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.SysUser'),
        ),
    ]
