# Generated by Django 3.0.6 on 2020-06-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200601_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysdataset',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sysfile',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.SysDataset'),
        ),
        migrations.AlterField(
            model_name='syspermission',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.SysDataset'),
        ),
    ]
