# Generated by Django 3.0.7 on 2020-06-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200602_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=512)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.SysDataset')),
            ],
            options={
                'db_table': 'search_index',
            },
        ),
    ]
