# Generated by Django 3.0.6 on 2020-06-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_searchindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.SysDataset')),
            ],
            options={
                'db_table': 'subject_index',
            },
        ),
    ]
