# Generated by Django 3.0.6 on 2020-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_subjectindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sysdataset',
            name='category',
        ),
        migrations.AddField(
            model_name='sysdataset',
            name='categories',
            field=models.ManyToManyField(to='mainpage.Category'),
        ),
    ]
