# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoiAuthor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'doi_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoiRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(blank=True, max_length=64, null=True)),
                ('suid', models.BigIntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('site_url', models.TextField(blank=True, null=True)),
                ('olcf_project_id', models.CharField(blank=True, max_length=8, null=True)),
                ('dataset_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('product_nos', models.CharField(blank=True, max_length=255, null=True)),
                ('doe_contract_nos', models.CharField(blank=True, max_length=255, null=True)),
                ('other_contract_nos', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_orgs', models.CharField(blank=True, max_length=1024, null=True)),
                ('sponsor_orgs', models.CharField(blank=True, max_length=1024, null=True)),
                ('contrib_orgs', models.CharField(blank=True, max_length=1024, null=True)),
                ('software_needed', models.CharField(blank=True, max_length=1024, null=True)),
                ('other_id_nos', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField()),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('doi_infix', models.CharField(blank=True, max_length=8, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_org', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('request_status', models.CharField(blank=True, max_length=12, null=True)),
                ('data_status', models.CharField(blank=True, max_length=15, null=True)),
                ('admin_suid', models.BigIntegerField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doi_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysDataset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('public', models.IntegerField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=256, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('structure', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('displayname', models.CharField(blank=True, max_length=128, null=True)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('profilephoto', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
    ]
