version: "3.4"
services:
  sdidb:
    container_name: sdidb
    image: postgres:12
    environment:
      POSTGRES_USER: sdidbp
      POSTGRES_PASSWORD: sdisdi
      POSTGRES_DB: sdidb
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
  sdifrontend:
    container_name: sdifrontend
    build:
      context: ..
      dockerfile: openshift/sdifrontend/Dockerfile
    environment:
      SDI_DATABASE_USER: sdidbp
      SDI_DATABASE_PASSWORD: sdisdi
      SDI_DATABASE_NAME: sdidb
      SDI_DATABASE_HOST: sdidb
      SDI_DATABASE_PORT: 5432 
      SOCIAL_AUTH_GLOBUS_KEY: db786b4f-5a50-47f5-bd13-9ea7f7d0599a
      SOCIAL_AUTH_GLOBUS_SECRET: tjxCHVIBGYNFnTFnAdMaOW5VfgZCw7PsHOyvjnzftQc=
    depends_on:
      - sdidb
    ports:
      - "5000:5000"
    links:
      - sdidb:sdidb
    volumes:
      - staticvolume:/app/static
  sdinginx:
    container_name: sdinginx
    build: 
      context: ..
      dockerfile: openshift/sdinginx/Dockerfile
    depends_on:
      - sdifrontend
    ports:
      - "8000:8000"
    links:
      - sdifrontend:sdifrontend
    volumes:
      - staticvolume:/usr/share/nginx/html/static
volumes:
  postgresvolume:
  staticvolume:

